rpc:
  url: "http://localhost:9944"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  num_accounts: 1
  chain_id: "MADARA_DEVNET"

run:
  concurrency: 1000
  shooters:
    - name: "transfer"
      shoot: 1000000
    - name: "mint"
      shoot: 0
  read_benches:
    - name: "Get Events"
      num_requests: 0
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

deployer:
  salt: "0x1"
  address: "0x008a1719e7ca19f3d91e8ef50a48fc456575f645497a1d55f30e3781f786afe4"
  signing_key: "0x514977443078cf1e0c36bc88b89ada9a46061a5cf728f40274caea21d76f174"
  legacy_account: false
